version: "3.9"
services:
  loader:
    build:
      context: .
      dockerfile: PatternsLoader.Dockerfile
    environment:
      DB_Settings:connectionString: "Server=db;Port=5432;Database=TheLife;User Id=postgres;password=123qwe!@#QWE;"
    depends_on:
      - db
  web:
    build:
      context: .
      args:
        REACT_APP_SERVER_ADDRESS: http://localhost:5129
        REACT_APP_BASE_PATH: /life
    ports:
      - "5129:5129"
    environment:
      DB_Settings:connectionString: "Server=db;Port=5432;Database=TheLife;User Id=postgres;password=123qwe!@#QWE;"
      URLS: "http://+:5129"
      ASPNETCORE_URLS: "http://+:5129"
    depends_on:
      - db
      - loader
  db:
    image: "postgres:14.4-alpine"
    environment:
      POSTGRES_PASSWORD: "123qwe!@#QWE"
    volumes:
      - "./LifeDataBase/DataBaseScripts/:/docker-entrypoint-initdb.d/"