create database "TheLife"
    with owner postgres;

\connect TheLife;

create table "LifeUsers"
(
    "Id"   uuid not null
        constraint "PK_LifeUsers"
            primary key,
    "Name" text not null
);

alter table "LifeUsers"
    owner to postgres;

create table "LifeStates"
(
    "Id"           bigint generated by default as identity
        constraint "PK_LifeStates"
            primary key,
    "LastChange"   timestamp with time zone not null,
    "Survivors"    text                     not null,
    "Name"         text                     not null,
    "UserEntityId" uuid                     not null
        constraint "FK_LifeStates_LifeUsers_UserEntityId"
            references "LifeUsers"
            on delete cascade
);

create table "Patterns"
(
    "Id"                 bigint generated by default as identity
        constraint "PK_Patterns"
            primary key,
    "Name"               text                     not null,
    "Description"        text                     not null,
    "PreviewImageBase64" text                     not null,
    "LastUpdate"         timestamp with time zone not null,
    "Survivors"          text                     not null
);

alter table "Patterns"
    owner to postgres;

